# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 107dba109f307ae4f0b8c5df99abc356c7091ce458e498f63918580108f1df4b06331b9e6d44f744149c8def816ffd8c93852d2700af77566d8ff766205402b4

test:
  secret_key_base: e85df1459e6709278fdca3b14d7e23923643ac1a0f330a2e2a140cd34a79f479259cb5af33531faba95c840cd47a19e0bceeaf429faaa945488c4f837c5e902b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
